version = "0.1"

[assemblers]
go = true
gas = false
nasm = false

[instruction_sets]
x86 = false
x86_64 = true
arm = true

[default_config]
assembler = "go"
instruction_set = "x86_64"

[default_config.opts]
diagnostics = false
default_diagnostics = false
