package tools

import (
	"strings"
	"unicode"
)

// CountryLanguage maps an international dial code prefix to country and official language metadata.
type CountryLanguage struct {
	DialCode    string
	CountryCode string
	CountryName string
	LangCode    string // ISO 639-1 code (e.g. "en", "es", "fr")
	LangName    string // Human-readable language name (e.g. "English", "Spanish")
}

// dialCodeList contains international dial codes ordered from longest prefix to shortest for prefix matching.
var dialCodeList = []CountryLanguage{
	// 4-digit prefixes
	{DialCode: "1809", CountryCode: "DO", CountryName: "Dominican Republic", LangCode: "es", LangName: "Spanish"},
	{DialCode: "1829", CountryCode: "DO", CountryName: "Dominican Republic", LangCode: "es", LangName: "Spanish"},
	{DialCode: "1849", CountryCode: "DO", CountryName: "Dominican Republic", LangCode: "es", LangName: "Spanish"},
	{DialCode: "1787", CountryCode: "PR", CountryName: "Puerto Rico", LangCode: "es", LangName: "Spanish"},
	{DialCode: "1939", CountryCode: "PR", CountryName: "Puerto Rico", LangCode: "es", LangName: "Spanish"},
	{DialCode: "1876", CountryCode: "JM", CountryName: "Jamaica", LangCode: "en", LangName: "English"},
	{DialCode: "1868", CountryCode: "TT", CountryName: "Trinidad and Tobago", LangCode: "en", LangName: "English"},
	{DialCode: "1242", CountryCode: "BS", CountryName: "Bahamas", LangCode: "en", LangName: "English"},
	{DialCode: "1246", CountryCode: "BB", CountryName: "Barbados", LangCode: "en", LangName: "English"},

	// 3-digit prefixes
	{DialCode: "212", CountryCode: "MA", CountryName: "Morocco", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "213", CountryCode: "DZ", CountryName: "Algeria", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "216", CountryCode: "TN", CountryName: "Tunisia", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "218", CountryCode: "LY", CountryName: "Libya", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "220", CountryCode: "GM", CountryName: "Gambia", LangCode: "en", LangName: "English"},
	{DialCode: "221", CountryCode: "SN", CountryName: "Senegal", LangCode: "fr", LangName: "French"},
	{DialCode: "222", CountryCode: "MR", CountryName: "Mauritania", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "223", CountryCode: "ML", CountryName: "Mali", LangCode: "fr", LangName: "French"},
	{DialCode: "224", CountryCode: "GN", CountryName: "Guinea", LangCode: "fr", LangName: "French"},
	{DialCode: "225", CountryCode: "CI", CountryName: "Ivory Coast", LangCode: "fr", LangName: "French"},
	{DialCode: "226", CountryCode: "BF", CountryName: "Burkina Faso", LangCode: "fr", LangName: "French"},
	{DialCode: "227", CountryCode: "NE", CountryName: "Niger", LangCode: "fr", LangName: "French"},
	{DialCode: "228", CountryCode: "TG", CountryName: "Togo", LangCode: "fr", LangName: "French"},
	{DialCode: "229", CountryCode: "BJ", CountryName: "Benin", LangCode: "fr", LangName: "French"},
	{DialCode: "230", CountryCode: "MU", CountryName: "Mauritius", LangCode: "en", LangName: "English"},
	{DialCode: "231", CountryCode: "LR", CountryName: "Liberia", LangCode: "en", LangName: "English"},
	{DialCode: "232", CountryCode: "SL", CountryName: "Sierra Leone", LangCode: "en", LangName: "English"},
	{DialCode: "233", CountryCode: "GH", CountryName: "Ghana", LangCode: "en", LangName: "English"},
	{DialCode: "234", CountryCode: "NG", CountryName: "Nigeria", LangCode: "en", LangName: "English"},
	{DialCode: "235", CountryCode: "TD", CountryName: "Chad", LangCode: "fr", LangName: "French"},
	{DialCode: "236", CountryCode: "CF", CountryName: "Central African Republic", LangCode: "fr", LangName: "French"},
	{DialCode: "237", CountryCode: "CM", CountryName: "Cameroon", LangCode: "fr", LangName: "French"},
	{DialCode: "238", CountryCode: "CV", CountryName: "Cape Verde", LangCode: "pt", LangName: "Portuguese"},
	{DialCode: "239", CountryCode: "ST", CountryName: "Sao Tome and Principe", LangCode: "pt", LangName: "Portuguese"},
	{DialCode: "240", CountryCode: "GQ", CountryName: "Equatorial Guinea", LangCode: "es", LangName: "Spanish"},
	{DialCode: "241", CountryCode: "GA", CountryName: "Gabon", LangCode: "fr", LangName: "French"},
	{DialCode: "242", CountryCode: "CG", CountryName: "Republic of the Congo", LangCode: "fr", LangName: "French"},
	{DialCode: "243", CountryCode: "CD", CountryName: "DR Congo", LangCode: "fr", LangName: "French"},
	{DialCode: "244", CountryCode: "AO", CountryName: "Angola", LangCode: "pt", LangName: "Portuguese"},
	{DialCode: "245", CountryCode: "GW", CountryName: "Guinea-Bissau", LangCode: "pt", LangName: "Portuguese"},
	{DialCode: "248", CountryCode: "SC", CountryName: "Seychelles", LangCode: "en", LangName: "English"},
	{DialCode: "249", CountryCode: "SD", CountryName: "Sudan", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "250", CountryCode: "RW", CountryName: "Rwanda", LangCode: "rw", LangName: "Kinyarwanda"},
	{DialCode: "251", CountryCode: "ET", CountryName: "Ethiopia", LangCode: "am", LangName: "Amharic"},
	{DialCode: "252", CountryCode: "SO", CountryName: "Somalia", LangCode: "so", LangName: "Somali"},
	{DialCode: "253", CountryCode: "DJ", CountryName: "Djibouti", LangCode: "fr", LangName: "French"},
	{DialCode: "254", CountryCode: "KE", CountryName: "Kenya", LangCode: "sw", LangName: "Swahili"},
	{DialCode: "255", CountryCode: "TZ", CountryName: "Tanzania", LangCode: "sw", LangName: "Swahili"},
	{DialCode: "256", CountryCode: "UG", CountryName: "Uganda", LangCode: "en", LangName: "English"},
	{DialCode: "257", CountryCode: "BI", CountryName: "Burundi", LangCode: "fr", LangName: "French"},
	{DialCode: "258", CountryCode: "MZ", CountryName: "Mozambique", LangCode: "pt", LangName: "Portuguese"},
	{DialCode: "260", CountryCode: "ZM", CountryName: "Zambia", LangCode: "en", LangName: "English"},
	{DialCode: "261", CountryCode: "MG", CountryName: "Madagascar", LangCode: "fr", LangName: "French"},
	{DialCode: "263", CountryCode: "ZW", CountryName: "Zimbabwe", LangCode: "en", LangName: "English"},
	{DialCode: "264", CountryCode: "NA", CountryName: "Namibia", LangCode: "en", LangName: "English"},
	{DialCode: "265", CountryCode: "MW", CountryName: "Malawi", LangCode: "en", LangName: "English"},
	{DialCode: "266", CountryCode: "LS", CountryName: "Lesotho", LangCode: "en", LangName: "English"},
	{DialCode: "267", CountryCode: "BW", CountryName: "Botswana", LangCode: "en", LangName: "English"},
	{DialCode: "268", CountryCode: "SZ", CountryName: "Eswatini", LangCode: "en", LangName: "English"},
	{DialCode: "269", CountryCode: "KM", CountryName: "Comoros", LangCode: "ar", LangName: "Arabic"},

	{DialCode: "351", CountryCode: "PT", CountryName: "Portugal", LangCode: "pt", LangName: "Portuguese"},
	{DialCode: "352", CountryCode: "LU", CountryName: "Luxembourg", LangCode: "fr", LangName: "French"},
	{DialCode: "353", CountryCode: "IE", CountryName: "Ireland", LangCode: "en", LangName: "English"},
	{DialCode: "354", CountryCode: "IS", CountryName: "Iceland", LangCode: "is", LangName: "Icelandic"},
	{DialCode: "355", CountryCode: "AL", CountryName: "Albania", LangCode: "sq", LangName: "Albanian"},
	{DialCode: "356", CountryCode: "MT", CountryName: "Malta", LangCode: "en", LangName: "English"},
	{DialCode: "357", CountryCode: "CY", CountryName: "Cyprus", LangCode: "el", LangName: "Greek"},
	{DialCode: "358", CountryCode: "FI", CountryName: "Finland", LangCode: "fi", LangName: "Finnish"},
	{DialCode: "359", CountryCode: "BG", CountryName: "Bulgaria", LangCode: "bg", LangName: "Bulgarian"},
	{DialCode: "370", CountryCode: "LT", CountryName: "Lithuania", LangCode: "lt", LangName: "Lithuanian"},
	{DialCode: "371", CountryCode: "LV", CountryName: "Latvia", LangCode: "lv", LangName: "Latvian"},
	{DialCode: "372", CountryCode: "EE", CountryName: "Estonia", LangCode: "et", LangName: "Estonian"},
	{DialCode: "373", CountryCode: "MD", CountryName: "Moldova", LangCode: "ro", LangName: "Romanian"},
	{DialCode: "374", CountryCode: "AM", CountryName: "Armenia", LangCode: "hy", LangName: "Armenian"},
	{DialCode: "375", CountryCode: "BY", CountryName: "Belarus", LangCode: "be", LangName: "Belarusian"},
	{DialCode: "376", CountryCode: "AD", CountryName: "Andorra", LangCode: "ca", LangName: "Catalan"},
	{DialCode: "377", CountryCode: "MC", CountryName: "Monaco", LangCode: "fr", LangName: "French"},
	{DialCode: "378", CountryCode: "SM", CountryName: "San Marino", LangCode: "it", LangName: "Italian"},
	{DialCode: "380", CountryCode: "UA", CountryName: "Ukraine", LangCode: "uk", LangName: "Ukrainian"},
	{DialCode: "381", CountryCode: "RS", CountryName: "Serbia", LangCode: "sr", LangName: "Serbian"},
	{DialCode: "382", CountryCode: "ME", CountryName: "Montenegro", LangCode: "sr", LangName: "Serbian"},
	{DialCode: "385", CountryCode: "HR", CountryName: "Croatia", LangCode: "hr", LangName: "Croatian"},
	{DialCode: "386", CountryCode: "SI", CountryName: "Slovenia", LangCode: "sl", LangName: "Slovenian"},
	{DialCode: "387", CountryCode: "BA", CountryName: "Bosnia and Herzegovina", LangCode: "bs", LangName: "Bosnian"},
	{DialCode: "389", CountryCode: "MK", CountryName: "North Macedonia", LangCode: "mk", LangName: "Macedonian"},
	{DialCode: "420", CountryCode: "CZ", CountryName: "Czech Republic", LangCode: "cs", LangName: "Czech"},
	{DialCode: "421", CountryCode: "SK", CountryName: "Slovakia", LangCode: "sk", LangName: "Slovak"},
	{DialCode: "423", CountryCode: "LI", CountryName: "Liechtenstein", LangCode: "de", LangName: "German"},

	{DialCode: "501", CountryCode: "BZ", CountryName: "Belize", LangCode: "en", LangName: "English"},
	{DialCode: "502", CountryCode: "GT", CountryName: "Guatemala", LangCode: "es", LangName: "Spanish"},
	{DialCode: "503", CountryCode: "SV", CountryName: "El Salvador", LangCode: "es", LangName: "Spanish"},
	{DialCode: "504", CountryCode: "HN", CountryName: "Honduras", LangCode: "es", LangName: "Spanish"},
	{DialCode: "505", CountryCode: "NI", CountryName: "Nicaragua", LangCode: "es", LangName: "Spanish"},
	{DialCode: "506", CountryCode: "CR", CountryName: "Costa Rica", LangCode: "es", LangName: "Spanish"},
	{DialCode: "507", CountryCode: "PA", CountryName: "Panama", LangCode: "es", LangName: "Spanish"},
	{DialCode: "509", CountryCode: "HT", CountryName: "Haiti", LangCode: "fr", LangName: "French"},
	{DialCode: "591", CountryCode: "BO", CountryName: "Bolivia", LangCode: "es", LangName: "Spanish"},
	{DialCode: "592", CountryCode: "GY", CountryName: "Guyana", LangCode: "en", LangName: "English"},
	{DialCode: "593", CountryCode: "EC", CountryName: "Ecuador", LangCode: "es", LangName: "Spanish"},
	{DialCode: "594", CountryCode: "GF", CountryName: "French Guiana", LangCode: "fr", LangName: "French"},
	{DialCode: "595", CountryCode: "PY", CountryName: "Paraguay", LangCode: "es", LangName: "Spanish"},
	{DialCode: "597", CountryCode: "SR", CountryName: "Suriname", LangCode: "nl", LangName: "Dutch"},
	{DialCode: "598", CountryCode: "UY", CountryName: "Uruguay", LangCode: "es", LangName: "Spanish"},

	{DialCode: "670", CountryCode: "TL", CountryName: "East Timor", LangCode: "pt", LangName: "Portuguese"},
	{DialCode: "673", CountryCode: "BN", CountryName: "Brunei", LangCode: "ms", LangName: "Malay"},
	{DialCode: "675", CountryCode: "PG", CountryName: "Papua New Guinea", LangCode: "en", LangName: "English"},
	{DialCode: "676", CountryCode: "TO", CountryName: "Tonga", LangCode: "en", LangName: "English"},
	{DialCode: "677", CountryCode: "SB", CountryName: "Solomon Islands", LangCode: "en", LangName: "English"},
	{DialCode: "678", CountryCode: "VU", CountryName: "Vanuatu", LangCode: "en", LangName: "English"},
	{DialCode: "679", CountryCode: "FJ", CountryName: "Fiji", LangCode: "en", LangName: "English"},
	{DialCode: "682", CountryCode: "CK", CountryName: "Cook Islands", LangCode: "en", LangName: "English"},
	{DialCode: "685", CountryCode: "WS", CountryName: "Samoa", LangCode: "en", LangName: "English"},

	{DialCode: "850", CountryCode: "KP", CountryName: "North Korea", LangCode: "ko", LangName: "Korean"},
	{DialCode: "852", CountryCode: "HK", CountryName: "Hong Kong", LangCode: "zh-TW", LangName: "Traditional Chinese"},
	{DialCode: "853", CountryCode: "MO", CountryName: "Macau", LangCode: "zh-TW", LangName: "Traditional Chinese"},
	{DialCode: "855", CountryCode: "KH", CountryName: "Cambodia", LangCode: "km", LangName: "Khmer"},
	{DialCode: "856", CountryCode: "LA", CountryName: "Laos", LangCode: "lo", LangName: "Lao"},
	{DialCode: "880", CountryCode: "BD", CountryName: "Bangladesh", LangCode: "bn", LangName: "Bengali"},
	{DialCode: "886", CountryCode: "TW", CountryName: "Taiwan", LangCode: "zh-TW", LangName: "Traditional Chinese"},

	{DialCode: "960", CountryCode: "MV", CountryName: "Maldives", LangCode: "dv", LangName: "Dhivehi"},
	{DialCode: "961", CountryCode: "LB", CountryName: "Lebanon", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "962", CountryCode: "JO", CountryName: "Jordan", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "963", CountryCode: "SY", CountryName: "Syria", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "964", CountryCode: "IQ", CountryName: "Iraq", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "965", CountryCode: "KW", CountryName: "Kuwait", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "966", CountryCode: "SA", CountryName: "Saudi Arabia", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "967", CountryCode: "YE", CountryName: "Yemen", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "968", CountryCode: "OM", CountryName: "Oman", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "970", CountryCode: "PS", CountryName: "Palestine", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "971", CountryCode: "AE", CountryName: "United Arab Emirates", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "972", CountryCode: "IL", CountryName: "Israel", LangCode: "he", LangName: "Hebrew"},
	{DialCode: "973", CountryCode: "BH", CountryName: "Bahrain", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "974", CountryCode: "QA", CountryName: "Qatar", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "975", CountryCode: "BT", CountryName: "Bhutan", LangCode: "dz", LangName: "Dzongkha"},
	{DialCode: "976", CountryCode: "MN", CountryName: "Mongolia", LangCode: "mn", LangName: "Mongolian"},
	{DialCode: "977", CountryCode: "NP", CountryName: "Nepal", LangCode: "ne", LangName: "Nepali"},
	{DialCode: "992", CountryCode: "TJ", CountryName: "Tajikistan", LangCode: "tg", LangName: "Tajik"},
	{DialCode: "993", CountryCode: "TM", CountryName: "Turkmenistan", LangCode: "tk", LangName: "Turkmen"},
	{DialCode: "994", CountryCode: "AZ", CountryName: "Azerbaijan", LangCode: "az", LangName: "Azerbaijani"},
	{DialCode: "995", CountryCode: "GE", CountryName: "Georgia", LangCode: "ka", LangName: "Georgian"},
	{DialCode: "996", CountryCode: "KG", CountryName: "Kyrgyzstan", LangCode: "ky", LangName: "Kyrgyz"},
	{DialCode: "998", CountryCode: "UZ", CountryName: "Uzbekistan", LangCode: "uz", LangName: "Uzbek"},

	// 2-digit prefixes
	{DialCode: "20", CountryCode: "EG", CountryName: "Egypt", LangCode: "ar", LangName: "Arabic"},
	{DialCode: "27", CountryCode: "ZA", CountryName: "South Africa", LangCode: "en", LangName: "English"},
	{DialCode: "30", CountryCode: "GR", CountryName: "Greece", LangCode: "el", LangName: "Greek"},
	{DialCode: "31", CountryCode: "NL", CountryName: "Netherlands", LangCode: "nl", LangName: "Dutch"},
	{DialCode: "32", CountryCode: "BE", CountryName: "Belgium", LangCode: "nl", LangName: "Dutch"},
	{DialCode: "33", CountryCode: "FR", CountryName: "France", LangCode: "fr", LangName: "French"},
	{DialCode: "34", CountryCode: "ES", CountryName: "Spain", LangCode: "es", LangName: "Spanish"},
	{DialCode: "36", CountryCode: "HU", CountryName: "Hungary", LangCode: "hu", LangName: "Hungarian"},
	{DialCode: "39", CountryCode: "IT", CountryName: "Italy", LangCode: "it", LangName: "Italian"},
	{DialCode: "40", CountryCode: "RO", CountryName: "Romania", LangCode: "ro", LangName: "Romanian"},
	{DialCode: "41", CountryCode: "CH", CountryName: "Switzerland", LangCode: "de", LangName: "German"},
	{DialCode: "43", CountryCode: "AT", CountryName: "Austria", LangCode: "de", LangName: "German"},
	{DialCode: "44", CountryCode: "GB", CountryName: "United Kingdom", LangCode: "en", LangName: "English"},
	{DialCode: "45", CountryCode: "DK", CountryName: "Denmark", LangCode: "da", LangName: "Danish"},
	{DialCode: "46", CountryCode: "SE", CountryName: "Sweden", LangCode: "sv", LangName: "Swedish"},
	{DialCode: "47", CountryCode: "NO", CountryName: "Norway", LangCode: "no", LangName: "Norwegian"},
	{DialCode: "48", CountryCode: "PL", CountryName: "Poland", LangCode: "pl", LangName: "Polish"},
	{DialCode: "49", CountryCode: "DE", CountryName: "Germany", LangCode: "de", LangName: "German"},
	{DialCode: "51", CountryCode: "PE", CountryName: "Peru", LangCode: "es", LangName: "Spanish"},
	{DialCode: "52", CountryCode: "MX", CountryName: "Mexico", LangCode: "es", LangName: "Spanish"},
	{DialCode: "53", CountryCode: "CU", CountryName: "Cuba", LangCode: "es", LangName: "Spanish"},
	{DialCode: "54", CountryCode: "AR", CountryName: "Argentina", LangCode: "es", LangName: "Spanish"},
	{DialCode: "55", CountryCode: "BR", CountryName: "Brazil", LangCode: "pt", LangName: "Portuguese"},
	{DialCode: "56", CountryCode: "CL", CountryName: "Chile", LangCode: "es", LangName: "Spanish"},
	{DialCode: "57", CountryCode: "CO", CountryName: "Colombia", LangCode: "es", LangName: "Spanish"},
	{DialCode: "58", CountryCode: "VE", CountryName: "Venezuela", LangCode: "es", LangName: "Spanish"},
	{DialCode: "60", CountryCode: "MY", CountryName: "Malaysia", LangCode: "ms", LangName: "Malay"},
	{DialCode: "61", CountryCode: "AU", CountryName: "Australia", LangCode: "en", LangName: "English"},
	{DialCode: "62", CountryCode: "ID", CountryName: "Indonesia", LangCode: "id", LangName: "Indonesian"},
	{DialCode: "63", CountryCode: "PH", CountryName: "Philippines", LangCode: "tl", LangName: "Tagalog"},
	{DialCode: "64", CountryCode: "NZ", CountryName: "New Zealand", LangCode: "en", LangName: "English"},
	{DialCode: "65", CountryCode: "SG", CountryName: "Singapore", LangCode: "en", LangName: "English"},
	{DialCode: "66", CountryCode: "TH", CountryName: "Thailand", LangCode: "th", LangName: "Thai"},
	{DialCode: "81", CountryCode: "JP", CountryName: "Japan", LangCode: "ja", LangName: "Japanese"},
	{DialCode: "82", CountryCode: "KR", CountryName: "South Korea", LangCode: "ko", LangName: "Korean"},
	{DialCode: "84", CountryCode: "VN", CountryName: "Vietnam", LangCode: "vi", LangName: "Vietnamese"},
	{DialCode: "86", CountryCode: "CN", CountryName: "China", LangCode: "zh-CN", LangName: "Simplified Chinese"},
	{DialCode: "90", CountryCode: "TR", CountryName: "Turkey", LangCode: "tr", LangName: "Turkish"},
	{DialCode: "91", CountryCode: "IN", CountryName: "India", LangCode: "hi", LangName: "Hindi"},
	{DialCode: "92", CountryCode: "PK", CountryName: "Pakistan", LangCode: "ur", LangName: "Urdu"},
	{DialCode: "93", CountryCode: "AF", CountryName: "Afghanistan", LangCode: "fa", LangName: "Persian"},
	{DialCode: "94", CountryCode: "LK", CountryName: "Sri Lanka", LangCode: "si", LangName: "Sinhala"},
	{DialCode: "95", CountryCode: "MM", CountryName: "Myanmar", LangCode: "my", LangName: "Burmese"},
	{DialCode: "98", CountryCode: "IR", CountryName: "Iran", LangCode: "fa", LangName: "Persian"},

	// 1-digit prefixes
	{DialCode: "1", CountryCode: "US", CountryName: "United States / Canada", LangCode: "en", LangName: "English"},
	{DialCode: "7", CountryCode: "RU", CountryName: "Russia / Kazakhstan", LangCode: "ru", LangName: "Russian"},
}

// knownLanguages maps common language codes and names (lowercased) to ISO 639-1 code and display name.
var knownLanguages = map[string][2]string{
	"af":          {"af", "Afrikaans"},
	"afrikaans":   {"af", "Afrikaans"},
	"am":          {"am", "Amharic"},
	"amharic":     {"am", "Amharic"},
	"ar":          {"ar", "Arabic"},
	"arabic":      {"ar", "Arabic"},
	"az":          {"az", "Azerbaijani"},
	"azerbaijani": {"az", "Azerbaijani"},
	"be":          {"be", "Belarusian"},
	"belarusian":  {"be", "Belarusian"},
	"bg":          {"bg", "Bulgarian"},
	"bulgarian":   {"bg", "Bulgarian"},
	"bn":          {"bn", "Bengali"},
	"bengali":     {"bn", "Bengali"},
	"bs":          {"bs", "Bosnian"},
	"bosnian":     {"bs", "Bosnian"},
	"ca":          {"ca", "Catalan"},
	"catalan":     {"ca", "Catalan"},
	"cs":          {"cs", "Czech"},
	"czech":       {"cs", "Czech"},
	"cy":          {"cy", "Welsh"},
	"welsh":       {"cy", "Welsh"},
	"da":          {"da", "Danish"},
	"danish":      {"da", "Danish"},
	"de":          {"de", "German"},
	"german":      {"de", "German"},
	"el":          {"el", "Greek"},
	"greek":       {"el", "Greek"},
	"en":          {"en", "English"},
	"english":     {"en", "English"},
	"es":          {"es", "Spanish"},
	"spanish":     {"es", "Spanish"},
	"et":          {"et", "Estonian"},
	"estonian":    {"et", "Estonian"},
	"fa":          {"fa", "Persian"},
	"persian":     {"fa", "Persian"},
	"farsi":       {"fa", "Persian"},
	"fi":          {"fi", "Finnish"},
	"finnish":     {"fi", "Finnish"},
	"fr":          {"fr", "French"},
	"french":      {"fr", "French"},
	"ga":          {"ga", "Irish"},
	"irish":       {"ga", "Irish"},
	"gl":          {"gl", "Galician"},
	"galician":    {"gl", "Galician"},
	"gu":          {"gu", "Gujarati"},
	"gujarati":    {"gu", "Gujarati"},
	"ha":          {"ha", "Hausa"},
	"hausa":       {"ha", "Hausa"},
	"he":          {"he", "Hebrew"},
	"hebrew":      {"he", "Hebrew"},
	"iw":          {"he", "Hebrew"},
	"hi":          {"hi", "Hindi"},
	"hindi":       {"hi", "Hindi"},
	"hr":          {"hr", "Croatian"},
	"croatian":    {"hr", "Croatian"},
	"ht":          {"ht", "Haitian Creole"},
	"hu":          {"hu", "Hungarian"},
	"hungarian":   {"hu", "Hungarian"},
	"hy":          {"hy", "Armenian"},
	"armenian":    {"hy", "Armenian"},
	"id":          {"id", "Indonesian"},
	"indonesian":  {"id", "Indonesian"},
	"ig":          {"ig", "Igbo"},
	"igbo":        {"ig", "Igbo"},
	"is":          {"is", "Icelandic"},
	"icelandic":   {"is", "Icelandic"},
	"it":          {"it", "Italian"},
	"italian":     {"it", "Italian"},
	"ja":          {"ja", "Japanese"},
	"japanese":    {"ja", "Japanese"},
	"ka":          {"ka", "Georgian"},
	"georgian":    {"ka", "Georgian"},
	"kk":          {"kk", "Kazakh"},
	"kazakh":      {"kk", "Kazakh"},
	"km":          {"km", "Khmer"},
	"khmer":       {"km", "Khmer"},
	"kn":          {"kn", "Kannada"},
	"kannada":     {"kn", "Kannada"},
	"ko":          {"ko", "Korean"},
	"korean":      {"ko", "Korean"},
	"ku":          {"ku", "Kurdish"},
	"kurdish":     {"ku", "Kurdish"},
	"ky":          {"ky", "Kyrgyz"},
	"kyrgyz":      {"ky", "Kyrgyz"},
	"la":          {"la", "Latin"},
	"latin":       {"la", "Latin"},
	"lo":          {"lo", "Lao"},
	"lao":         {"lo", "Lao"},
	"lt":          {"lt", "Lithuanian"},
	"lithuanian":  {"lt", "Lithuanian"},
	"lv":          {"lv", "Latvian"},
	"latvian":     {"lv", "Latvian"},
	"mg":          {"mg", "Malagasy"},
	"malagasy":    {"mg", "Malagasy"},
	"mi":          {"mi", "Maori"},
	"maori":       {"mi", "Maori"},
	"mk":          {"mk", "Macedonian"},
	"macedonian":  {"mk", "Macedonian"},
	"ml":          {"ml", "Malayalam"},
	"malayalam":   {"ml", "Malayalam"},
	"mn":          {"mn", "Mongolian"},
	"mongolian":   {"mn", "Mongolian"},
	"mr":          {"mr", "Marathi"},
	"marathi":     {"mr", "Marathi"},
	"ms":          {"ms", "Malay"},
	"malay":       {"ms", "Malay"},
	"mt":          {"mt", "Maltese"},
	"maltese":     {"mt", "Maltese"},
	"my":          {"my", "Burmese"},
	"burmese":     {"my", "Burmese"},
	"ne":          {"ne", "Nepali"},
	"nepali":      {"ne", "Nepali"},
	"nl":          {"nl", "Dutch"},
	"dutch":       {"nl", "Dutch"},
	"no":          {"no", "Norwegian"},
	"norwegian":   {"no", "Norwegian"},
	"ny":          {"ny", "Chichewa"},
	"chichewa":    {"ny", "Chichewa"},
	"pa":          {"pa", "Punjabi"},
	"punjabi":     {"pa", "Punjabi"},
	"pl":          {"pl", "Polish"},
	"polish":      {"pl", "Polish"},
	"ps":          {"ps", "Pashto"},
	"pashto":      {"ps", "Pashto"},
	"pt":          {"pt", "Portuguese"},
	"portuguese":  {"pt", "Portuguese"},
	"ro":          {"ro", "Romanian"},
	"romanian":    {"ro", "Romanian"},
	"ru":          {"ru", "Russian"},
	"russian":     {"ru", "Russian"},
	"rw":          {"rw", "Kinyarwanda"},
	"kinyarwanda": {"rw", "Kinyarwanda"},
	"sd":          {"sd", "Sindhi"},
	"si":          {"si", "Sinhala"},
	"sinhala":     {"si", "Sinhala"},
	"sk":          {"sk", "Slovak"},
	"slovak":      {"sk", "Slovak"},
	"sl":          {"sl", "Slovenian"},
	"slovenian":   {"sl", "Slovenian"},
	"so":          {"so", "Somali"},
	"somali":      {"so", "Somali"},
	"sq":          {"sq", "Albanian"},
	"albanian":    {"sq", "Albanian"},
	"sr":          {"sr", "Serbian"},
	"serbian":     {"sr", "Serbian"},
	"su":          {"su", "Sundanese"},
	"sv":          {"sv", "Swedish"},
	"swedish":     {"sv", "Swedish"},
	"sw":          {"sw", "Swahili"},
	"swahili":     {"sw", "Swahili"},
	"ta":          {"ta", "Tamil"},
	"tamil":       {"ta", "Tamil"},
	"te":          {"te", "Telugu"},
	"telugu":      {"te", "Telugu"},
	"tg":          {"tg", "Tajik"},
	"tajik":       {"tg", "Tajik"},
	"th":          {"th", "Thai"},
	"thai":        {"th", "Thai"},
	"tl":          {"tl", "Tagalog"},
	"tagalog":     {"tl", "Tagalog"},
	"filipino":    {"tl", "Tagalog"},
	"tr":          {"tr", "Turkish"},
	"turkish":     {"tr", "Turkish"},
	"uk":          {"uk", "Ukrainian"},
	"ukrainian":   {"uk", "Ukrainian"},
	"ur":          {"ur", "Urdu"},
	"urdu":        {"ur", "Urdu"},
	"uz":          {"uz", "Uzbek"},
	"uzbek":       {"uz", "Uzbek"},
	"vi":          {"vi", "Vietnamese"},
	"vietnamese":  {"vi", "Vietnamese"},
	"xh":          {"xh", "Xhosa"},
	"yi":          {"yi", "Yiddish"},
	"yo":          {"yo", "Yoruba"},
	"yoruba":      {"yo", "Yoruba"},
	"zh":          {"zh-CN", "Simplified Chinese"},
	"chinese":     {"zh-CN", "Simplified Chinese"},
	"zh-cn":       {"zh-CN", "Simplified Chinese"},
	"zh-tw":       {"zh-TW", "Traditional Chinese"},
	"zu":          {"zu", "Zulu"},
}

// CleanPhoneNumber removes non-digit characters from a phone number string.
func CleanPhoneNumber(phone string) string {
	var sb strings.Builder
	for _, r := range phone {
		if unicode.IsDigit(r) {
			sb.WriteRune(r)
		}
	}
	return sb.String()
}

// DetectOwnerCountryLanguage matches a phone number against international calling code prefixes
// and returns the country and official language metadata.
func DetectOwnerCountryLanguage(phone string) (CountryLanguage, bool) {
	clean := CleanPhoneNumber(phone)
	if clean == "" {
		return CountryLanguage{
			DialCode:    "1",
			CountryCode: "US",
			CountryName: "United States",
			LangCode:    "en",
			LangName:    "English",
		}, false
	}

	for _, entry := range dialCodeList {
		if strings.HasPrefix(clean, entry.DialCode) {
			return entry, true
		}
	}

	// Fallback to English
	return CountryLanguage{
		DialCode:    "1",
		CountryCode: "US",
		CountryName: "Default",
		LangCode:    "en",
		LangName:    "English",
	}, false
}

// NormalizeLanguageCode checks if a token matches a known language code or name.
func NormalizeLanguageCode(input string) (code string, name string, ok bool) {
	clean := strings.ToLower(strings.TrimSpace(input))
	clean = strings.TrimPrefix(clean, "to:")
	clean = strings.TrimPrefix(clean, "[")
	clean = strings.TrimSuffix(clean, "]")

	if meta, exists := knownLanguages[clean]; exists {
		return meta[0], meta[1], true
	}
	return "", "", false
}
